name: flutter_widget_binder
description: A Flutter package for efficient state management with notifiers, async states, debouncing, undo/redo, and multiple state grouping.
version: 0.0.1+1
repository: https://github.com/NgoTaiCo/flutter_widget_binder

license: Apache 2.0

environment:
  sdk: ^3.5.4
 
dependencies:
  flutter:
    sdk: flutter 
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter 
  flutter_lints: ^4.0.0
 
flutter:
  uses-material-design: true