name: flutter_widget_binder
description: "flutter_widget_binder is a Flutter package designed for managing application states efficiently. The package provides various state management solutions, including simple state notifiers, asynchronous state notifiers, debounce functionality, undo/redo capabilities, and multiple state grouping. These tools help manage the state of your application in a modular and scalable way." 
version: 0.0.1+1
repository: https://github.com/NgoTaiCo/flutter_widget_binder

license: Apache 2.0

environment:
  sdk: ^3.5.4
 
dependencies:
  flutter:
    sdk: flutter 
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter 
  flutter_lints: ^4.0.0
 
flutter:
  uses-material-design: true